name: "Draft new release"

on:
  workflow_dispatch

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: Disable recursive install
        run: echo "recursive-install=false" >> .npmrc

      - name: Install workspace modules
        run: pnpm install

      - name: Version Packages
        uses: changesets/action@master
        with:
          version: pnpm changeset version
          commit: "chore: Version Packages"
          title: "chore: Version Packages"

      - name: Install modules
        run: pnpm install -r

      - name: Build
        run: pnpm run build

      - name: Publish Packages
        uses: changesets/action@master
        with:
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
